
- name: addusers and groups
  group:
    name: btsync
    gid: 1001
    state: present

- name: general packages
  apt:
    name:
      - cpulimit
      - htop
      - git
      - python-pip
      - nano
      - wget
      - man
    state : latest
