# ---
- name: create container and add user and key
  lxc_container:
    name: "{{ name }}"
    container_log: true
    template: ubuntu
    state: started
    template_options: --release {{ release }}

- name: copy template sources.list
  template: src=sources.list dest=/var/lib/lxc/{{ name }}/rootfs/etc/apt/sources.list owner=root group=root mode="0644"

- name: install minimal requirements to work with ansible
  lxc_container:
    name: "{{ name }}"
    container_command: |
      deluser ubuntu #&&  adduser -disabled-password --gecos ""  --gid {{ user_botgid }}  {{ user_bot }}
      useradd {{ user_bot }} -s /bin/bash -m -U
      echo -e "tempass\ntempass" | passwd {{ user_bot }}
      mkdir /home/{{ user_botgid }}/.ssh
    container_config:
      - "lxc.mount.entry = /data         data     none bind,create=dir 0 0"
      - "lxc.start.auto = {{ startauto }}"

- name: allow sudo commands
  lineinfile:
    dest: /var/lib/lxc/{{ name }}/rootfs/etc/sudoers
    state: present
    line: '{{ user_bot }} ALL=(ALL) NOPASSWD: ALL'

- name: add authorized_keys
  file: path=/var/lib/lxc/{{ name }}/rootfs/home/ubuntu state=absent

- name: add authorized_keys
  file: path=/var/lib/lxc/{{ name }}/rootfs/home/agalan/.ssh/ mode=0700  owner={{ user_bot }} group={{ user_botgid }} state=directory

- name: Copy SSH key
  copy: src=files/key dest=/var/lib/lxc/{{ name }}/rootfs/home/agalan/.ssh/authorized_keys mode=0600  owner={{ user_bot }} group={{ user_botgid }}

- name: install minimal requirements
  become_user: agalan
  command: ssh {{name}}.lxc "sudo apt update && sudo apt -y install python-simplejson"
